
/* Drop Tables */

DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS STOCK_FAIR_PRICE;
DROP TABLE IF EXISTS FAIR_PRICE_CALCULATION_METHOD;
DROP TABLE IF EXISTS FINANCIAL_STATEMENTS;
DROP TABLE IF EXISTS STOCK_PRICE;
DROP TABLE IF EXISTS STOCK_BASIC_INFO;
DROP TABLE IF EXISTS USER_INFO;




/* Create Tables */

-- 게시판
CREATE TABLE BOARD
(
	-- ID
	ID int NOT NULL,
	-- USER_ID
	USER_ID int NOT NULL,
	-- TITLE
	TITLE char NOT NULL,
	-- DETAIL
	DETAIL char NOT NULL,
	-- HITS
	HITS int DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


-- 적정가격계산방법
CREATE TABLE FAIR_PRICE_CALCULATION_METHOD
(
	-- 코드 : 적정주가산출방법코드
	CODE char NOT NULL,
	-- 이름 : 적정주가산출방법명
	NAME char,
	-- 공식 : 적정가격계산방법공식
	FORMULA char,
	PRIMARY KEY (CODE)
) WITHOUT OIDS;


-- 제무재표
CREATE TABLE FINANCIAL_STATEMENTS
(
	-- 표준코드 : KRX에 등록된 표준 코드
	STANDARD_CODE char NOT NULL,
	-- 당기순이익
	NET_INCOME int,
	-- 법인세비용
	INCOME_TAX_EXPENSE int
) WITHOUT OIDS;


-- 종목기본정보
CREATE TABLE STOCK_BASIC_INFO
(
	-- 표준코드 : KRX에 등록된 표준 코드
	STANDARD_CODE char NOT NULL,
	-- 단축코드 : 단축코드
	SHORT_CODE char,
	PRIMARY KEY (STANDARD_CODE)
) WITHOUT OIDS;


-- 주식적정가격
CREATE TABLE STOCK_FAIR_PRICE
(
	-- 기준년
	BASE_YEAR char,
	-- 기준분기 : 분기
	BASE_QUARTER_YEAR int,
	-- 표준코드 : KRX에 등록된 표준 코드
	STANDARD_CODE char NOT NULL,
	-- 가격 : 주식적정가격
	PRICE int,
	-- 코드 : 적정주가산출방법코드
	CODE char NOT NULL
) WITHOUT OIDS;


-- 주식가격
CREATE TABLE STOCK_PRICE
(
	-- 표준코드 : KRX에 등록된 표준 코드
	STANDARD_CODE char NOT NULL,
	-- 기준일
	REFERENCE_DATE date,
	-- 가격
	PRICE int
) WITHOUT OIDS;


-- 사용자_정보
CREATE TABLE USER_INFO
(
	-- ID
	ID int NOT NULL,
	-- NAME
	NAME char,
	-- PASSWORD
	PASSWORD char,
	-- EMAIL
	EMAIL char,
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE STOCK_FAIR_PRICE
	ADD FOREIGN KEY (CODE)
	REFERENCES FAIR_PRICE_CALCULATION_METHOD (CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FINANCIAL_STATEMENTS
	ADD FOREIGN KEY (STANDARD_CODE)
	REFERENCES STOCK_BASIC_INFO (STANDARD_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE STOCK_FAIR_PRICE
	ADD FOREIGN KEY (STANDARD_CODE)
	REFERENCES STOCK_BASIC_INFO (STANDARD_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE STOCK_PRICE
	ADD FOREIGN KEY (STANDARD_CODE)
	REFERENCES STOCK_BASIC_INFO (STANDARD_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE BOARD IS '게시판';
COMMENT ON COLUMN BOARD.ID IS 'ID';
COMMENT ON COLUMN BOARD.USER_ID IS 'USER_ID';
COMMENT ON COLUMN BOARD.TITLE IS 'TITLE';
COMMENT ON COLUMN BOARD.DETAIL IS 'DETAIL';
COMMENT ON COLUMN BOARD.HITS IS 'HITS';
COMMENT ON TABLE FAIR_PRICE_CALCULATION_METHOD IS '적정가격계산방법';
COMMENT ON COLUMN FAIR_PRICE_CALCULATION_METHOD.CODE IS '코드 : 적정주가산출방법코드';
COMMENT ON COLUMN FAIR_PRICE_CALCULATION_METHOD.NAME IS '이름 : 적정주가산출방법명';
COMMENT ON COLUMN FAIR_PRICE_CALCULATION_METHOD.FORMULA IS '공식 : 적정가격계산방법공식';
COMMENT ON TABLE FINANCIAL_STATEMENTS IS '제무재표';
COMMENT ON COLUMN FINANCIAL_STATEMENTS.STANDARD_CODE IS '표준코드 : KRX에 등록된 표준 코드';
COMMENT ON COLUMN FINANCIAL_STATEMENTS.NET_INCOME IS '당기순이익';
COMMENT ON COLUMN FINANCIAL_STATEMENTS.INCOME_TAX_EXPENSE IS '법인세비용';
COMMENT ON TABLE STOCK_BASIC_INFO IS '종목기본정보';
COMMENT ON COLUMN STOCK_BASIC_INFO.STANDARD_CODE IS '표준코드 : KRX에 등록된 표준 코드';
COMMENT ON COLUMN STOCK_BASIC_INFO.SHORT_CODE IS '단축코드 : 단축코드';
COMMENT ON TABLE STOCK_FAIR_PRICE IS '주식적정가격';
COMMENT ON COLUMN STOCK_FAIR_PRICE.BASE_YEAR IS '기준년';
COMMENT ON COLUMN STOCK_FAIR_PRICE.BASE_QUARTER_YEAR IS '기준분기 : 분기';
COMMENT ON COLUMN STOCK_FAIR_PRICE.STANDARD_CODE IS '표준코드 : KRX에 등록된 표준 코드';
COMMENT ON COLUMN STOCK_FAIR_PRICE.PRICE IS '가격 : 주식적정가격';
COMMENT ON COLUMN STOCK_FAIR_PRICE.CODE IS '코드 : 적정주가산출방법코드';
COMMENT ON TABLE STOCK_PRICE IS '주식가격';
COMMENT ON COLUMN STOCK_PRICE.STANDARD_CODE IS '표준코드 : KRX에 등록된 표준 코드';
COMMENT ON COLUMN STOCK_PRICE.REFERENCE_DATE IS '기준일';
COMMENT ON COLUMN STOCK_PRICE.PRICE IS '가격';
COMMENT ON TABLE USER_INFO IS '사용자_정보';
COMMENT ON COLUMN USER_INFO.ID IS 'ID';
COMMENT ON COLUMN USER_INFO.NAME IS 'NAME';
COMMENT ON COLUMN USER_INFO.PASSWORD IS 'PASSWORD';
COMMENT ON COLUMN USER_INFO.EMAIL IS 'EMAIL';



