
/* Drop Tables */

DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS USER_INFO;




/* Create Tables */

-- 게시판
CREATE TABLE BOARD
(
	-- ID
	ID int NOT NULL,
	-- USER_ID
	USER_ID int NOT NULL,
	-- TITLE
	TITLE char NOT NULL,
	-- DETAIL
	DETAIL char NOT NULL,
	-- HITS
	HITS int DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID)
) WITHOUT OIDS;


-- 사용자_정보
CREATE TABLE USER_INFO
(
	-- ID
	ID int NOT NULL,
	-- NAME
	NAME char,
	-- PASSWORD
	PASSWORD char,
	-- EMAIL
	EMAIL char,
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE BOARD
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USER_INFO (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE BOARD IS '게시판';
COMMENT ON COLUMN BOARD.ID IS 'ID';
COMMENT ON COLUMN BOARD.USER_ID IS 'USER_ID';
COMMENT ON COLUMN BOARD.TITLE IS 'TITLE';
COMMENT ON COLUMN BOARD.DETAIL IS 'DETAIL';
COMMENT ON COLUMN BOARD.HITS IS 'HITS';
COMMENT ON TABLE USER_INFO IS '사용자_정보';
COMMENT ON COLUMN USER_INFO.ID IS 'ID';
COMMENT ON COLUMN USER_INFO.NAME IS 'NAME';
COMMENT ON COLUMN USER_INFO.PASSWORD IS 'PASSWORD';
COMMENT ON COLUMN USER_INFO.EMAIL IS 'EMAIL';



